FROM public.ecr.aws/lambda/python:3.9

RUN pip3 install --upgrade pip
RUN yum install postgresql-devel gcc -y
COPY django_app ${LAMBDA_TASK_ROOT}/django_app
COPY consumer_service ${LAMBDA_TASK_ROOT}/
COPY consumer_service/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]
