# Generated by Django 4.2.4 on 2024-10-29 14:54

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_call_prompt', models.CharField(default='\nYou will receive a random note text. Analyze the note text and look for actionable items.\n\nInstructions:\n1. Identify actionable items in the text, which may include tasks, follow-ups, reminders, or any statements implying a required action.\n2. For each actionable item found, create a corresponding entry in a todo list.\n3. Additionally, create a maximum of three suitable unique categories for the note.\n4. Maintain the original language of the user\'s input, even if it is not in English.\n5. If no actionable items exist in the text, respond with an empty JSON object in the format {"tasks": [], "categories": []}.\n\nOutput:\n- Return a JSON object with two keys:\n  - "tasks": an array containing each actionable item as a string.\n  - "categories": an array with a maximum of three unique categories related to the note.\n- If there are no actionable items, return {"tasks": [], "categories": []}.\n\nExample Output:\n{\n    "tasks": [\n        "Follow up with client on project status",\n        "Prepare presentation for next week\'s meeting",\n        "Order supplies for office"\n    ],\n    "categories": [\n        "Client Management",\n        "Presentations",\n        "Supplies"\n    ]\n}\n', max_length=4000)),
                ('note_prompt', models.CharField(default='Your mission is to assist in transforming user input into a coherent and well-structured note for a note-taking application, adhering to the following guidelines:\n\n### Content Enhancement:\n1. **Correct Typos:** Identify and correct any typographical errors present in the original input.\n2. **Maintain Original Language:** Preserve the original language of the user\'s input, do NOT change the language to english if the user\'s input is not in english.\n3. **Minimal Addition:** While maintaining coherency, only introduce minimal additions to the content. Refrain from adding content that can be measured in sentences.\n\n### Markdown Formatting:\n4. **Structured Formatting:** Implement markdown markup language to format the note, ensuring it is easy to read and well-organized.\n5. **Heading and Subheading:** If possible, distinguish between main points and subpoints, utilizing appropriate markdown headers.\n\n### General Instructions:\n6. **Do Not Add a Footer:** Ensure that no footer or additional closing statements are introduced at the end of the note.\n7. **Coherency is Key:** Ensure that any changes or additions maintain the coherence and intended message of the original note.\n\nExample:\n```markdown\nUser Input: "Meting with John on 10/10, discuss: budgets 2023, marketing strategy, and new hires"\n\nTransformed Note:\n# Meeting with John on 10/10\n\n## Discussions:\n  - Budgets for 2023\n  - Marketing strategy\n  - New hires\n```\n\n### Please ensure the following:\n- **Accuracy:** Guarantee that the information accuracy is preserved during the transformation and editing.\n- **User-Friendliness:** The final note should be user-friendly and easily navigable for reference.\n\nRemember, your primary role is to enhance and format user input into a cleaner, well-structured, and professional-looking note while strictly adhering to the given instructions and maintaining the original intent and language.', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_posted', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAISettingsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_prompt', models.CharField(default='Your mission is to assist in transforming user input into a coherent and well-structured note for a note-taking application, adhering to the following guidelines:\n\n### Content Enhancement:\n1. **Correct Typos:** Identify and correct any typographical errors present in the original input.\n2. **Maintain Original Language:** Preserve the original language of the user\'s input, do NOT change the language to english if the user\'s input is not in english.\n3. **Minimal Addition:** While maintaining coherency, only introduce minimal additions to the content. Refrain from adding content that can be measured in sentences.\n\n### Markdown Formatting:\n4. **Structured Formatting:** Implement markdown markup language to format the note, ensuring it is easy to read and well-organized.\n5. **Heading and Subheading:** If possible, distinguish between main points and subpoints, utilizing appropriate markdown headers.\n\n### General Instructions:\n6. **Do Not Add a Footer:** Ensure that no footer or additional closing statements are introduced at the end of the note.\n7. **Coherency is Key:** Ensure that any changes or additions maintain the coherence and intended message of the original note.\n\nExample:\n```markdown\nUser Input: "Meting with John on 10/10, discuss: budgets 2023, marketing strategy, and new hires"\n\nTransformed Note:\n# Meeting with John on 10/10\n\n## Discussions:\n  - Budgets for 2023\n  - Marketing strategy\n  - New hires\n```\n\n### Please ensure the following:\n- **Accuracy:** Guarantee that the information accuracy is preserved during the transformation and editing.\n- **User-Friendliness:** The final note should be user-friendly and easily navigable for reference.\n\nRemember, your primary role is to enhance and format user input into a cleaner, well-structured, and professional-looking note while strictly adhering to the given instructions and maintaining the original intent and language.', max_length=4000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('processed_note', models.TextField(default='Note is being processed by GPT-4..', max_length=4000)),
                ('original_note', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todos', models.JSONField(blank=True, default=core.models.Note.get_default_todos, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
